.catalog:
  name: "Owncloud"
  version: "v0.1-educaas"
  description: "Library service powered by Owncloud"
  uuid: owncloud-0
  minimum_rancher_version: v0.51.0
  questions:
   - variable: owncloud_server
      label: "OwnCloud server name"
      type: "string"
      required: true

${owncloud_server}: